### ISSUE TITLE
alarm problems

### ISSUE THREAD

**Issue by kammaii** [kammaii/akorean#14]
1. In notification.js, it sends hour and minute through scheduelNotification(hour, minute). But it doesn't consider the time and it just alarm soon when I set time.

2. When I click the alarm message, it doesn't open the app.

3. I code to send 'null' through scheduleNotification function when the alarm switch is OFF. But I'm not sure it would be ok because the function has 2 parameters. (notifications.js line 32)

**Comment by upgradingdave** [comment]
> 1. In notification.js, it sends hour and minute through scheduelNotification(hour, minute). But it doesn't consider the time and it just alarm soon when I set time.

I fixed a few bugs related to setting the time and switch in localstorage. I also fixed a problem with the communication between javascript and android java code. This is fixed!

> 2. When I click the alarm message, it doesn't open the app.

Sorry about that. Originally I had it working. But I commented out a line for testing. I added the code back in, and now the app will open when you click the message. Fixed!

> 3. I code to send 'null' through scheduleNotification function when the alarm switch is OFF. But I'm not sure it would be ok because the function has 2 parameters. (notifications.js line 32)

Yes, we still need to be able to cancel alarms, we can get this working during our meeting.
