### ISSUE TITLE
getElementById is null!

### ISSUE THREAD

**Issue by kammaii** [kammaii/akorean#2]
I want to make a function to make little box of consonants. 
Actually I wanted to make it to jquery like below. (std_ass_1.html, line 15~21)

 ` let consonantArray = ["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ", "ㅂ", "ㅅ", "ㅇ", "ㅈ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ", "ㄲ", "ㄸ", "ㅃ", "ㅆ", "ㅉ"];`

  `function() {`
  `  for(let i=0; i<consonantArray.length; i++) {`
 `     $("#consonants").html(consonantArray[i]);`
`    }`
`  }`

But it didn't work.
So I tried to make it to javascript getElementById like below. (std_ass_1.html, line 23~36)

`  function createCharacters(character) {`
`    let newElement = document.createElement("p");`
`    let newCharacterNode = document.createTextNode(character);`
`    newElement.appendChild(newCharacterNode);`
`    return newElement;`
`  }`
`  let currentDiv = document.getElementById("consonants")`
`  console.log(currentDiv);`

`  for(let i=0; i<consonantArray.length; i++) {`
`    let consonant = createCharacters(consonantArray[i]);`
`    console.log(consonant);`
`    currentDiv.appendChild(consonant);`
`  }`

But the result of `console.log(currentDiv);` is `null`.

I think the way of jquery is more simple than javascript in this problem. 
What do you think?

**Comment by upgradingdave** [comment]
I took a look and noticed a few things: 

1. The browser will render the body from top to bottom. So, the `<script>` tag was running before the `consonants` div was available. 

2. This code will replace the contents of the `consonants` div with each element in the array. 

```
    for(let i=0; i<consonantArray.length; i++) {
      $("#consonants").html(consonantArray[i]);
    }
```
I think you want to create a new div every time. So I changed to create multiple div tags with class `consonants`:  
```
  for(let i=0; i<consonantArray.length; i++) {
    $("#consonants-container").append("<div class=\"consonants\">"+consonantArray[i]+"</div>");
  }
```
3. You can use plain javascript as well! Just depends on your preference. I think most people find jquery easier, but sometimes I like plain javascript better than jquery ;-) I updated your plain javascript to work as well.
